<?php

namespace Tests\Functional\API\V1\Mobile;

use App\Traits\TestResponseJsonTrait;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class PathwaysControllerMobileTest extends TestCase
{
    use DatabaseMigrations;
    use TestResponseJsonTrait;

    private const PAGING = 10;
    private const DEVELOPER = ['developer@admin.com', 'Developer'];
    private const SUPER_ADMIN = [
        'happence-super-admin@admin.com',
        'Happence Super Admin'
    ];
    private const TENANT_ADMIN_1 = [
        'tenant-1-admin@admin.com',
        'Tenant Admin'
    ];
    private const TENANT_USER = [
        'tenant-2-root-dep-1-user-1@admin.com',
        'Tenant-2 Root-Dep-1 User-1'
    ];
    private const STRUCTURE_SINGLE = [
        'success',
        'code',
        'data' =>
            [
                "id",
                "type_id",
                "modules" => [
                    [
                        "id",
                        "name",
                        "order",
                        "widget_type_id",
                        "specific_id",
                        "previous_id",
                        "created_at",
                        "updated_at"
                    ]
                ],
                "created_at",
                "updated_at"
            ],
        'message'
    ];

    private const STRUCTURE_MODULE = [
        'success',
        'code',
        'data' =>
            [
                "id",
                "name",
                "order",
                "widget_type_id",
                "specific_id",
                "previous_id",
                "widget_included" =>
                    [
                        "id",
                        "widget_type_id",
                        "button_text",
                        "settings_id",
                        "created_at",
                        "updated_at"
                    ],
                "widget_settings" => [],
                "created_at",
                "updated_at"
            ],
        'message'
    ];

    private const STRUCTURE_SIMPLE = [
        'success',
        'code',
        'data',
        'message'
    ];

    private const STRUCTURE_SIMPLEST = [
        'success',
        'code',
        'message'
    ];

    private const STRUCTURE_PAGING = [
        'success',
        'code',
        'data' =>
            [
                'current_page',
                'data' =>
                    [
                        [
                            'status',
                            'id',
                            'name',
                            'department_id',
                            'sequence_id',
                            'author',
                            'thumb',
                            'description',
                            'likes',
                            'length_unit',
                            'length',
                            'offline',
                            'mood_tracker',
                            'feedback',
                            'created_at',
                            'updated_at'
                        ]
                    ],
                'first_page_url',
                'from',
                'last_page',
                'last_page',
                'last_page_url',
                'links',
                'next_page_url',
                'path',
                'per_page',
                'prev_page_url',
                'to',
                'total'
            ],
        'message'
    ];

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->artisan('db:seed --class=TestsPathwaysSeeder');
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function testExample()
    {
        $this->assertTrue(true);
    }

    /**
     * Check seeder.
     *
     * @return void
     */
    public function testSeeder()
    {
        $types = DB::table('sequence_types')->where('id', 1)->first();
        $this->assertEquals('course', $types->name);

        $modules = DB::table('widget_simple_questions')->get();
        $answers = json_decode($modules[0]->questions)->sets[0]->answers;
        $this->assertEquals('Answer 2. Text.', $answers[1]->answer);

        $modules  = DB::table('widget_free_text_questions')->get();
        $question = json_decode($modules[0]->questions)->sets[0]->question;
        $this->assertEquals('Question Free Text 1. Text.', $question);

        $modules  = DB::table('widget_slider_questions')->get();
        $question = json_decode($modules[0]->questions)->sets[0]->question;
        $this->assertEquals('Question Slider 1. Text.', $question);

        $modules = DB::table('widget_media_questions')->get();
        $media   = json_decode($modules[3]->questions)->sets[1]->media;
        $this->assertEquals('modules/media_question/19-343x219.png', $media);

        $modules = DB::table('widget_media_answer_questions')->get();
        $media   = json_decode($modules[1]->questions)->sets[1]->answers[1]->media;
        $this->assertEquals('modules/media_question/837-343x219.png', $media);

        $modules = DB::table('widget_articles')->get();
        $body    = $modules[0]->body;
        $this->assertEquals('Simple row text.', $body);

        $modules = DB::table('widget_link_externals')->get();
        $body    = $modules[0]->body;
        $this->assertEquals('Link body text', $body);

        $modules = DB::table('widget_link_internals')->get();
        $cta     = $modules[0]->cta;
        $this->assertEquals('Visit Home', $cta);

        $modules = DB::table('widget_onboardings')->get();
        $file    = $modules[3]->file;
        $this->assertEquals(null, $file);

        $modules = DB::table('module_sequences')->get();
        $this->assertCount(17, $modules);
    }

    /**
     * Check indexFiltered With Pagination For Tenant User
     *
     * @return void
     */
    public function testIndexWithPaginationForTenantUser()
    {
        $token = $this->loginByEmail(
            self::TENANT_USER[0],
            self::TENANT_USER[1]
        );

        // Request
        $response = $this
            ->post(
                'api/mobile/v1/pathways?token=' . $token . '&page=' . 1
            );

        // Check response status
        $response->assertStatus(200);

        // Check response structure
        $response->assertJsonStructure(self::STRUCTURE_PAGING);

        $resp = $this->responseParsed($response);

        $this->assertEquals(true, $resp['success']);
        $this->assertEquals(200, $resp['code']);
        $this->assertCount(10, $resp['data']['data']);
        $this->assertEquals('Course-2 Tenant-1', $resp['data']['data'][1]['name']);
        $this->assertEquals(3, $resp['data']['data'][1]['department_id']);
        $this->assertEquals(1, $resp['data']['data'][1]['sequence_id']);
        $this->assertEquals('Author Course-2', $resp['data']['data'][1]['author']);
        $this->assertEquals('thumb-2.jpg', $resp['data']['data'][1]['thumb']);
        $this->assertEquals(8, $resp['data']['data'][1]['modules_count']);
        $this->assertEquals(
            'Description for Course 2',
            $resp['data']['data'][1]['description']
        );
        $this->assertEquals('active', $resp['data']['data'][1]['status']);
        $this->assertEquals('m', $resp['data']['data'][1]['length_unit']);
        $this->assertEquals(30, $resp['data']['data'][1]['length']);
        $this->assertEquals(false, $resp['data']['data'][1]['offline']);
        $this->assertEquals(false, $resp['data']['data'][1]['mood_tracker']);
        $this->assertEquals(false, $resp['data']['data'][1]['feedback']);
        $this->assertEquals("List of Pathways.", $resp['message']);
        $this->assertEquals(1, $resp['data']['current_page']);
        $this->assertEquals(15, $resp['data']['total']);
    }

    /**
     * Check indexFiltered With Pagination, Category For Tenant User
     *
     * @return void
     */
    public function testIndexFilteredWithPaginationCategoryForTenantUser()
    {
        $token = $this->loginByEmail(
            self::TENANT_USER[0],
            self::TENANT_USER[1]
        );

        $data = [
            'category_id' => 1
        ];

        // Request
        $response = $this
            ->post(
                'api/mobile/v1/pathways?token=' . $token . '&page=' . 1,
                $data
            );

        // Check response status
        $response->assertStatus(200);

        // Check response structure
        $response->assertJsonStructure(self::STRUCTURE_PAGING);

        $resp = $this->responseParsed($response);

        $this->assertEquals(true, $resp['success']);
        $this->assertEquals(200, $resp['code']);
        $this->assertCount(8, $resp['data']['data']);
        $this->assertEquals('Course-3 Tenant-2', $resp['data']['data'][1]['name']);
        $this->assertEquals(8, $resp['data']['total']);
        $this->assertEquals(1, $resp['data']['current_page']);
    }

    /**
     * Check indexFiltered With Pagination, Wrong Category For Tenant User
     *
     * @return void
     */
    public function testIndexFilteredWithPaginationWrongCategoryForTenantUser()
    {
        $token = $this->loginByEmail(
            self::TENANT_USER[0],
            self::TENANT_USER[1]
        );

        $data = [
            'category_id' => 999
        ];

        // Request
        $response = $this
            ->post(
                'api/mobile/v1/pathways?token=' . $token . '&page=' . 1,
                $data
            );

        // Check response status
        $response->assertStatus(204);
    }

    /**
     * Check indexFiltered With Pagination, Empty Category For Tenant User
     *
     * @return void
     */
    public function testIndexFilteredWithPaginationEmptyCategoryForTenantUser()
    {
        $token = $this->loginByEmail(
            self::TENANT_USER[0],
            self::TENANT_USER[1]
        );

        $data = [
            'category_id' => ''
        ];

        // Request
        $response = $this->withHeader('Accept', 'application/json')
            ->post(
                'api/mobile/v1/pathways?token=' . $token . '&page=' . 1,
                $data
            );

        // Check response status
        $response->assertStatus(422);
    }

    /**
     * Check indexFiltered With Pagination, Sort For Tenant User
     *
     * @return void
     */
    public function testIndexFilteredWithPaginationSortLengthForTenantUser()
    {
        $token = $this->loginByEmail(
            self::TENANT_USER[0],
            self::TENANT_USER[1]
        );

        $data = [
            'length' => 'desc'
        ];

        // Request
        $response = $this
            ->post(
                'api/mobile/v1/pathways?token=' . $token . '&page=' . 1,
                $data
            );

        // Check response status
        $response->assertStatus(200);

        // Check response structure
        $response->assertJsonStructure(self::STRUCTURE_PAGING);

        $resp = $this->responseParsed($response);

        $this->assertEquals(true, $resp['success']);
        $this->assertEquals(200, $resp['code']);
        $this->assertCount(10, $resp['data']['data']);
        $this->assertEquals('Course-15 Tenant-1', $resp['data']['data'][0]['name']);
        $this->assertEquals(15, $resp['data']['total']);
        $this->assertEquals(1, $resp['data']['current_page']);
    }

    /**
     * Check indexFiltered With Pagination, Full Parameters For Tenant User
     *
     * @return void
     */
    public function testIndexFilteredWithPaginationFullParametersForTenantUser()
    {
        $token = $this->loginByEmail(
            self::TENANT_USER[0],
            self::TENANT_USER[1]
        );

        $data = [
            'length'      => 'asc',
            'category_id' => 2
        ];

        // Request
        $response = $this
            ->post(
                'api/mobile/v1/pathways?token=' . $token . '&page=' . 1,
                $data
            );

        // Check response status
        $response->assertStatus(200);

        // Check response structure
        $response->assertJsonStructure(self::STRUCTURE_PAGING);

        $resp = $this->responseParsed($response);

        $this->assertEquals(true, $resp['success']);
        $this->assertEquals(200, $resp['code']);
        $this->assertCount(7, $resp['data']['data']);
        $this->assertEquals('Course-2 Tenant-1', $resp['data']['data'][0]['name']);
        $this->assertEquals(7, $resp['data']['total']);
        $this->assertEquals(1, $resp['data']['current_page']);
    }

    /**
     * Check indexFiltered With Pagination, Full Parameters For Tenant User
     *
     * @return void
     */
    public function testIndexFilteredWithPaginationFullParametersWrongPageForTenantUser()
    {
        $token = $this->loginByEmail(
            self::TENANT_USER[0],
            self::TENANT_USER[1]
        );

        $data = [
            'length'      => 'asc',
            'category_id' => 2
        ];

        // Request
        $response = $this
            ->post(
                'api/mobile/v1/pathways?token=' . $token . '&page=' . 3,
                $data
            );

        // Check response status
        $response->assertStatus(204);
    }

    /**
     * Check indexFiltered With Pagination For Tenant Admin
     *
     * @return void
     */
    public function testIndexFilteredWithPaginationForTenantAdmin()
    {
        $token = $this->loginByEmail(
            self::TENANT_ADMIN_1[0],
            self::TENANT_ADMIN_1[1]
        );

        // Request
        $response = $this
            ->post(
                'api/mobile/v1/pathways?token=' . $token . '&page=' . 3
            );

        // Check response status
        $response->assertStatus(403);
    }

    /**
     * Check indexFiltered For Guest
     *
     * @return void
     */
    public function testIndexFilteredForGuest()
    {
        // Request
        $response = $this
            ->post(
                'api/mobile/v1/pathways?token=' . '&page=' . 3
            );

        // Check response status
        $response->assertStatus(401);
    }
}
