<?php

namespace Tests\Functional\API\V1\CMS;

use App\Models\WidgetArticle;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;
use App\Traits\TestResponseJsonTrait;
use App\Models\MoodTracker;
use App\Models\MoodTrackerToActivity;

/**
 * Class WidgetArticleControllerTest
 *
 * PHP version 7.4
 *
 * @category Seeder
 * @package  Database\Seeders
 * @author  Nerush Mykola <mykola.nerush@intellicagroup.com>
 * @license  BSD License
 * @link     Database\Seeders
 */
class WidgetArticleControllerTest extends TestCase
{
    use DatabaseMigrations;
    use TestResponseJsonTrait;

    private const ROLE_DEVELOPER = ['developer@admin.com', 'Developer'];

    public function setUp(): void
    {

        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('db:seed --class=TestsWidgetArticleSeeder');

    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function testExample()
    {
        $this->assertTrue(true);
    }

    /**
     * Check seeder.
     *
     * @return void
     */
    public function testSeeder()
    {
        $this->assertEquals(1, DB::table('widget_articles')->count());

        $widgetArticle = DB::table('widget_articles')->where('id', 1)->first();
        $this->assertEquals(WidgetArticle::getWidgetTypeId(), $widgetArticle->widget_type_id);
        $this->assertEquals('body', $widgetArticle->body);
        $this->assertEquals('button_text', $widgetArticle->button_text);
    }

    /**
     * Check Delete
     *
     * @return void
     */
    public function testDeleteWidgetArticle(): void
    {
        $token = $this->loginByEmail(self::ROLE_DEVELOPER[0], self::ROLE_DEVELOPER[1]);

        // Request
        $response = $this->delete('api/cms/v1/widget-article/1?token=' . $token);

        // Check response status
        $response->assertStatus(200);

        // Check response structure
        $response->assertJsonStructure(
            [
                'success',
                'code',
                'data',
                'message'
            ]
        );
        $responseJSON = json_decode($response->getContent(), true);
        $success = $responseJSON['success'];  // array
        $code = $responseJSON['code'];     // array
        $message = $responseJSON['message'];  // array
        $data = $responseJSON['data'];     // array

        $this->assertEquals(true, $success);
        $this->assertEquals(200, $code);
        $this->assertEquals(null, $data);
        $this->assertEquals('Deleted The  widget Article.', $message);

        $removedWidgetArticle = WidgetArticle::whereId(1)->first();
        $this->assertEquals(null, $removedWidgetArticle);
    }

    /**
     * Check Delete
     *
     * @return void
     */
    public function testDeleteWidgetArtiicleByGuest(): void
    {
        // Request
        $response = $this->delete('api/cms/v1/widget-article/3');

        // Check response status
        $response->assertStatus(401);
    }

    /**
     * Check Index
     *
     * @return void
     */
    public function testIndexForDeveloper(): void
    {
        $token = $this->loginByEmail(self::ROLE_DEVELOPER[0], self::ROLE_DEVELOPER[1]);

        // Request
        $response = $this->get('api/cms/v1/widget-article?token=' . $token);

        // Check response status
        $response->assertStatus(200);

        // Check response structure
        $response->assertJsonStructure(
            [
                'success',
                'code',
                'data' =>
                    [
                        [
                            'id',
                            'widget_type_id',
                            'body',
                            'button_text',
                            'settings_id',
                            'created_at',
                            'updated_at',
                            'widget_settings'
                        ]
                    ],
                'message'
            ]
        );

        $responseJSON = json_decode($response->getContent(), true);
        $data = $responseJSON['data'];     // array
        $WidgetArticle = $data[0];

        $this->assertEquals(true, $responseJSON['success']);
        $this->assertEquals(200, $responseJSON['code']);
        $this->assertCount(1, $responseJSON['data']);
        $this->assertEquals('WidgetArticle Index', $responseJSON['message']);
        $this->assertEquals(1, $WidgetArticle['id']);
        $this->assertEquals(WidgetArticle::getWidgetTypeId(), $WidgetArticle['widget_type_id']);
        $this->assertEquals('body', $WidgetArticle['body']);
        $this->assertEquals('button_text', $WidgetArticle['button_text']);
    }


    /**
     * Check Index for Guest
     *
     * @return void
     */
    public function testIndexForGuest(): void
    {
        // Request
        $response = $this->get('api/cms/v1/widget-article');

        // Check response status
        $response->assertStatus(401);
    }

    /**
     * Check Specific widget article
     *
     * @return void
     */
    public function testShowSpecificWidgetArticle(): void
    {
        // Login via super-admin
        $token = $this->loginByEmail(self::ROLE_DEVELOPER[0], self::ROLE_DEVELOPER[1]);

        // Request
        $response = $this->get('api/cms/v1/widget-article/1?token=' . $token);

        // Check response status
        $response->assertStatus(200);

        // Check response structure
        $response->assertJsonStructure(
            [
                'success',
                'code',
                'data' =>
                    [
                        'id',
                        'widget_type_id',
                        'body',
                        'button_text',
                        'settings_id',
                        'created_at',
                        'updated_at',
                        'widget_settings'
                    ],
                'message'
            ]
        );
        $responseJSON = json_decode($response->getContent(), true);
        $data = $responseJSON['data'];     // array

        $this->assertEquals(true, $responseJSON['success']);
        $this->assertEquals(200, $responseJSON['code']);
        $this->assertEquals('Got Specific widget Article.', $responseJSON['message']);
        $this->assertCount(8, $data);
        $this->assertEquals(1, $data['id']);
        $this->assertEquals(WidgetArticle::getWidgetTypeId(), $data['widget_type_id']);
        $this->assertEquals('body', $data['body']);
        $this->assertEquals('button_text', $data['button_text']);
    }


    /**
     * Check Specific Widget Article for Guest
     *
     * @return void
     */
    public function testSpecificWidgetArticleForGuest(): void
    {
        // Request
        $response = $this->get('api/cms/v1/widget-article/2');

        // Check response status
        $response->assertStatus(401);
    }

    /**
     * Check Store a new Widget Article
     *
     * @return void
     */
    public function testStoreNewWidgetArticle(): void
    {
        $token = $this->loginByEmail(self::ROLE_DEVELOPER[0], self::ROLE_DEVELOPER[1]);

        // Create data
        $data = [
            'body' => 'body',
            'button_text' => 'button_text',
            'settings' => [
                'completion_time' => '13',
            ]
        ];

        // Request
        $response = $this->post('api/cms/v1/widget-article?token=' . $token, $data);

        // Check response status
        $response->assertStatus(200);

        // Check response structure
        $response->assertJsonStructure(
            [
                'success',
                'code',
                'data' =>
                    [
                        'id',
                        'widget_type_id',
                        'body',
                        'button_text',
                        'settings_id',
                        'created_at',
                        'updated_at',
                        'widget_settings',
                    ],
                'message'
            ]
        );
        $responseJSON = json_decode($response->getContent(), true);
        $data = $responseJSON['data'];     // array

        $this->assertEquals(true, $responseJSON['success']);
        $this->assertEquals(200, $responseJSON['code']);
        $this->assertEquals('Created new widget Article.', $responseJSON['message']);
        $this->assertCount(8, $data);
        $this->assertEquals(WidgetArticle::getWidgetTypeId(), $data['widget_type_id']);
        $this->assertEquals('body', $data['body']);
        $this->assertEquals('button_text', $data['button_text']);
    }

    /**
     * Check Update Widget Article
     *
     * @return void
     */
    public function testUpdateWidgetArticle(): void
    {
        $token = $this->loginByEmail(self::ROLE_DEVELOPER[0], self::ROLE_DEVELOPER[1]);

        // Create data
        $data = [
            'body' => 'body',
            'button_text' => 'button_text',
            'settings' => [
                'completion_time' => '13',
            ]
        ];

        // Request
        $response = $this->put('api/cms/v1/widget-article/1?token=' . $token, $data);

        // Check response status
        $response->assertStatus(200);

        // Check response structure
        $response->assertJsonStructure(
            [
                'success',
                'code',
                'data' =>
                    [
                        'id',
                        'widget_type_id',
                        'body',
                        'button_text',
                        'settings_id',
                        'created_at',
                        'updated_at',
                        'widget_settings',
                    ],
                'message'
            ]
        );
        $responseJSON = json_decode($response->getContent(), true);
        $data = $responseJSON['data'];     // array

        $this->assertEquals(true, $responseJSON['success']);
        $this->assertEquals(200, $responseJSON['code']);
        $this->assertEquals('Updated the widget Article.', $responseJSON['message']);
        $this->assertCount(8, $data);
        $this->assertEquals(WidgetArticle::getWidgetTypeId(), $data['widget_type_id']);
        $this->assertEquals('body', $data['body']);
        $this->assertEquals('button_text', $data['button_text']);
    }

    /**
     * Check Update WidgetArticle For Guest
     *
     * @return void
     */
    public function testUpdateWidgetArticleForGuest(): void
    {
        // Create data
        $data = [
            'body' => 'body',
            'button_text' => 'button_text',
        ];

        // Request
        $response = $this->put('api/cms/v1/widget-article/1', $data);

        // Check response status
        $response->assertStatus(401);
    }
}
